meson: Fix linking error when compiling with GCC
Before the following error occurred. Interestingly this
only happens when compiling with GCC, but not with Clang.

/usr/bin/ld: /tmp/audacious.Cizrbf.ltrans0.ltrans.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status